# Generated by Django 3.2 on 2021-06-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210626_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('path', models.CharField(max_length=150)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
